In [2]:
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
b=np.zeros(10)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
c=np.arange(2,21,2)
print(c)

[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
d=np.arange(1,10)
print(d)

[1 2 3 4 5 6 7 8 9]


In [5]:
d=np.arange(1,10)
print(d)
print(d.sum())

[1 2 3 4 5 6 7 8 9]
45


In [1]:
import numpy as np

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([[1,2,3],[4,5,6],[9,10,11],[11,12,13]])

print("1D Array:",arr1)
print("2D Array:\n",arr2)

zeros=np.zeros((3,4))
ones=np.ones((2,3))
identity=np.eye(5)

print("Zeros:\n",zeros)
print("Ones:\n",ones)
print("Identity Matrix:\n",identity)

arange_arr=np.arange(1,45,2)
linspace_arr=np.linspace(1,2,4)

print("Arange:",arange_arr)
print("Linspace:",linspace_arr)

rand_arr=np.random.rand(2,3)
print("Random Array:\n",rand_arr)
otp=((rand_arr*1000000)).astype(int)
print("Random Array:\n",otp)

1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [1.         1.33333333 1.66666667 2.        ]
Random Array:
 [[0.76482354 0.69335571 0.04436305]
 [0.77511193 0.43775826 0.25051667]]
Random Array:
 [[764823 693355  44363]
 [775111 437758 250516]]


In [6]:
import numpy as np

matrix=np.arange(1,13).reshape(4,3)
print("Matrix:\n",matrix)
print("Transpose:\n",matrix.T)

arr=np.array([10,20,30,40])
print("Original Array:",arr)
print("Array + 5:",arr-5)
print("Array squared:",arr**2)

print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n",np.dot(A,B))

unsorted=np.array([3,1,4,1,5,9])
print("Sorted Array:",np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [ 5 15 25 35]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]
